### ISSUE TITLE
width calculation fails when upgrading from 8.3

### ISSUE THREAD

**Issue by Alderaic-zz** [handsontable/handsontable#667]
Hi, upgrading from 8.3 to 8.23, I get consistantly the same error when loading my table:

``` javascript
Uncaught TypeError: Property 'renderer' of object #<Object> is not a function jquery.handsontable.full.js:2665
Handsontable.TableView.applyCellTypeMethod jquery.handsontable.full.js:2665
walkontableConfig.cellRenderer jquery.handsontable.full.js:2514
WalkontableSettings._getSetting jquery.handsontable.full.js:6588
WalkontableSettings.getSetting jquery.handsontable.full.js:6582
Walkontable.getSetting jquery.handsontable.full.js:5613
WalkontableTable._doDraw jquery.handsontable.full.js:6930
WalkontableTable.draw jquery.handsontable.full.js:6841
Walkontable.draw jquery.handsontable.full.js:5581
Handsontable.TableView.render jquery.handsontable.full.js:2653
init jquery.handsontable.full.js:1307
(anonymous function) jquery.handsontable.full.js:2316
p.extend.each jquery-1.8.1.min.js:2
p.fn.p.each jquery-1.8.1.min.js:2
$.fn.handsontable jquery.handsontable.full.js:2301
(anonymous function) functions.js:2556
k jquery-1.8.1.min.js:2
l.fireWith jquery-1.8.1.min.js:2
y jquery-1.8.1.min.js:2
d
```

This is what I use to load my table,

``` javascript
    $("#example1").handsontable({
    data: clusters,
    minSpareRows: 0,
    startRows: 1,
    startCols: 1,
    rowHeaders: data.products,
    colHeaders: data.headers,
    columns: data.columns,
  currentRowClassName: 'currentRow',
  currentColClassName: 'currentCol',
  autoWrapRow: false
  });
```

My Data is this:

``` javascript
{
    "clusters": [{
            "product": "Alternate Numbers|Default",
            "product_uid": "4147",
            "profile_uid": "4132",
            "bought": "1000",
            "available": 0,
            "sku_association_uid": "853",
            "locked": 0,
            "2863": "0"
        }, {
            "product": "Attendant Console|Default",
            "product_uid": "4075",
            "profile_uid": "4060",
            "bought": "150",
            "available": 0,
            "sku_association_uid": "858",
            "locked": 0,
            "2863": "0"
        }, {
            "product": "Auto Attendant|Default",
            "product_uid": "4076",
            "profile_uid": "4061",
            "bought": "925",
            "available": 0,
            "sku_association_uid": "857",
            "locked": 0,
            "2863": "0"
        }, {
            "product": "Call Center \/ ACD - Standard|Default",
            "product_uid": "4036",
            "profile_uid": "4021",
            "bought": "150",
            "available": 0,
            "sku_association_uid": "852",
            "locked": 0,
            "2863": "0"
        }, {
            "product": "CommPilot Express|Default",
            "product_uid": "4157",
            "profile_uid": "4142",
            "bought": "6000",
            "available": 0,
            "sku_association_uid": "860",
            "locked": 0,
            "2863": "0"
        }, {
            "product": "Consumer Mobility|Mixed Model",
            "product_uid": "4080",
            "profile_uid": "4065",
            "bought": "1000",
            "available": 0,
            "sku_association_uid": "862",
            "locked": 0,
            "2863": "0"
        }, {
            "product": "Operating System|Default",
            "product_uid": "4041",
            "profile_uid": "4026",
            "bought": "10000",
            "available": 0,
            "sku_association_uid": "863",
            "locked": 0,
            "2863": "0"
        }, {
            "product": "Outlook Integration|Default",
            "product_uid": "4098",
            "profile_uid": "4083",
            "bought": "10000",
            "available": 0,
            "sku_association_uid": "849",
            "locked": 0,
            "601": "0",
            "2863": "0"
        }, {
            "product": "Premium Enterprise|Mixed Model",
            "product_uid": "4033",
            "profile_uid": "4018",
            "bought": "2500",
            "available": 0,
            "sku_association_uid": "861",
            "locked": 0,
            "601": "3500",
            "2863": "0"
        }, {
            "product": "Premium Residential \/ SOHO|Mixed Model",
            "product_uid": "4062",
            "profile_uid": "4047",
            "bought": "2000",
            "available": 0,
            "sku_association_uid": "859",
            "locked": 0,
            "2863": "2000"
        }, {
            "product": "Remote Office|Default",
            "product_uid": "4137",
            "profile_uid": "4122",
            "bought": "1000",
            "available": 0,
            "sku_association_uid": "866",
            "locked": 0,
            "2863": "0"
        }, {
            "product": "Shared Call Appearance|Default",
            "product_uid": "4136",
            "profile_uid": "4121",
            "bought": "2000",
            "available": 0,
            "sku_association_uid": "856",
            "locked": 0,
            "2863": "0",
            "5620": "0"
        }, {
            "product": "Standard Enterprise|Mixed Model",
            "product_uid": "4064",
            "profile_uid": "4049",
            "bought": "3000",
            "available": 0,
            "sku_association_uid": "865",
            "locked": 0,
            "2863": "0"
        }, {
            "product": "Standard Residential \/ SOHO|Mixed Model",
            "product_uid": "4034",
            "profile_uid": "4019",
            "bought": "208000",
            "available": 0,
            "sku_association_uid": "855",
            "locked": 0,
            "2863": "20000"
        }, {
            "product": "Unified Messaging - Fax|Default",
            "product_uid": "4073",
            "profile_uid": "4058",
            "bought": "7500",
            "available": 0,
            "sku_association_uid": "6694",
            "locked": 0,
            "2863": "0"
        }, {
            "product": "Unified Messaging - Standard|Default",
            "product_uid": "4039",
            "profile_uid": "4024",
            "bought": "151000",
            "available": 0,
            "sku_association_uid": "868",
            "locked": 0,
            "2863": "0"
        }, {
            "product": "Web Conferencing|Default",
            "product_uid": "4091",
            "profile_uid": "4076",
            "bought": "1000002",
            "available": 0,
            "sku_association_uid": "848",
            "locked": 0,
            "2863": "0"
        }
    ],
    "customer_id": "C10099",
    "products": ["Alternate Numbers|Default", "Attendant Console|Default", "Auto Attendant|Default", "Call Center \/ ACD - Standard|Default", "CommPilot Express|Default", "Consumer Mobility|Mixed Model", "Operating System|Default", "Outlook Integration|Default", "Premium Enterprise|Mixed Model", "Premium Residential \/ SOHO|Mixed Model", "Remote Office|Default", "Shared Call Appearance|Default", "Standard Enterprise|Mixed Model", "Standard Residential \/ SOHO|Mixed Model", "Unified Messaging - Fax|Default", "Unified Messaging - Standard|Default", "Web Conferencing|Default"],
    "headers": ["<br>Bought Qte", "<br>Available", "<br>Locked", "Production<br>AS Cluster 1", "Production<br>AS Cluster 2", "Production<br>AS Cluster 3", "Production<br>AS Cluster 4"],
    "columns": [{
            "data": "bought",
            "type": {
                "renderer": "myReadonlyRenderer"
            },
            "readOnly": true
        }, {
            "data": "available",
            "type": {
                "renderer": "myReadonlyRenderer"
            },
            "readOnly": true,
            "remainerColumn": true
        }, {
            "data": "locked",
            "type": {
                "renderer": "myReadonlyRenderer"
            },
            "readOnly": true
        }, {
            "data": 601,
            "type": {
                "renderer": "myReadonlyRenderer"
            }
        }, {
            "data": 2863,
            "type": {
                "renderer": "myReadonlyRenderer"
            }
        }, {
            "data": 4993,
            "type": {
                "renderer": "myReadonlyRenderer"
            }
        }, {
            "data": 5620,
            "type": {
                "renderer": "myReadonlyRenderer"
            }
        }
    ]
}
```

I was able to display some stuff by changing the width but then it only displays headers and the first row before giving me that error again.

I went through the changelog a couple times, but I cannot find what changed except in 8.3 but that's what I was already on.
