### ISSUE TITLE
Handsontable - Double Click event

### ISSUE THREAD

**Issue by tromss** [handsontable/handsontable#3100]
Hi every one! I have a problem with handsontable.
I would like to get the double click event to do opération before save my data.
I see some same subject but no issue.
so i have use this link : https://gist.github.com/pezon/2b6ee291f1d286461d97?signup=true
 
and I have this error : Handsontable.eventManager is not a function
do you think it's possible to solve this error with this file eventManager.js? 

I'm clearly lost, please help me :)

**Comment by AMBudnik** [comment]
Hi @tromss as https://gist.github.com/pezon/2b6ee291f1d286461d97?signup=true is not a part of a Handsontable library please create a topic at stackoverflow: https://stackoverflow.com/search?q=handsontable

**Comment by jimmyye** [comment]
Updated the gist to work with Handsontable v0.38.1
https://gist.github.com/jimmyye/46b2ee89c4c0385f29ed5b737fe70da7
