### ISSUE TITLE
Typescript error 2304 since updating from 0.31.0 to 0.33.0

### ISSUE THREAD

**Issue by snaplemouton** [handsontable/handsontable#4419]
### Description
After changing my project's handsontable version from 0.31.0 to 0.33.0, my application can no longer compile due to typescript errors in handsontable package.

I am using Angular 4 as well as ng2-handsontable.

See picture below for errors.
Also getting a single error in ng2-handsontable package when using handsontable version 0.33.0.
`node_modules/ng2-handsontable/handsontable.component.d.ts(149,32): error TS2304: Cannot find name 'Handsontable'.`

I uninstalled handsontable 0.33.0 and reinstalled 0.31.0 and it started working again.

My systemjs.config.js mapping for handsontable and ng2-handsontable:
```
'handsontable': 'npm:handsontable/dist/handsontable.full.js',
'ng2-handsontable': 'npm:ng2-handsontable/bundles/ng2-handsontable.umd.js'
```

My package.json dependencies: 
```
"dependencies": {
    "@angular/animations": "~4.0.0",
    "@angular/common": "~4.0.0",
    "@angular/compiler": "~4.0.0",
    "@angular/core": "~4.0.0",
    "@angular/forms": "~4.0.0",
    "@angular/http": "~4.0.0",
    "@angular/platform-browser": "~4.0.0",
    "@angular/platform-browser-dynamic": "~4.0.0",
    "@angular/router": "~4.0.0",
    "angular-in-memory-web-api": "~0.3.0",
    "angular2-moment": "^1.3.3",
    "core-js": "^2.4.1",
    "handsontable": "^0.31.0",
    "moment": "^2.18.1",
    "ng2-handsontable": "^1.0.3",
    "ngx-bootstrap": "^1.6.6",
    "reflect": "^0.1.3",
    "rxjs": "5.0.1",
    "systemjs": "0.19.40",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "concurrently": "^3.2.0",
    "lite-server": "^2.2.2",
    "typescript": "~2.1.0",
    "canonical-path": "0.0.2",
    "tslint": "^3.15.1",
    "lodash": "^4.16.4",
    "jasmine-core": "~2.4.1",
    "karma": "^1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~4.0.14",
    "rimraf": "^2.5.4",
    "@types/node": "^6.0.46",
    "@types/jasmine": "2.5.36"
  }
```

### Steps to reproduce
1. npm install --save handsontable
2. npm start

### Terminal
The error list goes on for > 100 of the same error on different lines.
![image](https://user-images.githubusercontent.com/4615537/28376780-fed346be-6c78-11e7-834b-89465b92630f.png)

### Your environment
* Handsontable version: 0.33.0
* Browser Name and version: N/A
* Operating System: Windows 10
* IDE: Visual Studio Code
* npm version: 3.10.10

**Comment by swistach** [comment]
Hi @snaplemouton, you have to use TypeScript 2.2 or higher (`object` type was introduced in v2.2).
Currently we're working on our official wrapper here: https://github.com/handsontable/angular2-handsontable/issues/2

**Comment by AMBudnik** [comment]
Thanks for sharing @swistach I think that we can close the issue
