### ISSUE TITLE
[9.0.0] The angular wrapper fails to build on the current 9.0rc.

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#8099]
### Description
When trying to build `@handsontable/angular` with the current `develop` (04edde9) containing HyperFormula, errors get thrown:

```
ERROR: ../../node_modules/hyperformula/typings/Config.d.ts:362:5 - error TS18028: Private identifiers are only available when targeting ECMAScript 2015 and higher.

362     #private;
        ~~~~~~~~

An unhandled exception occurred: ../../node_modules/hyperformula/typings/Config.d.ts:362:5 - error TS18028: Private identifiers are only available when targeting ECMAScript 2015 and higher.

362     #private;
        ~~~~~~~~
```

The error seems to be caused by a private member in HF declared with a `#`, which makes it incompatible with the current version of TypeScript used in our codebase.

### Steps to reproduce
```bash
> npm run clean:node_modules
> npm run all build
```

**Comment by aninde** [comment]
Fixed by https://github.com/handsontable/hyperformula/pull/681.
