### ISSUE TITLE
ERROR TypeError: this.indexesSequence.addLocalHook is not a function in Prod Mode

### ISSUE THREAD

**Issue by rapelt** [handsontable/handsontable#7586]
### Description
I am working on an Angular v10.2.4 project and using Handsontable v8.3.1. When I build in prod mode with the AOT flag and Build Optimiser on I get the follow error when trying to generate a table.

ERROR TypeError: this.indexesSequence.addLocalHook is not a function.

### Steps to reproduce
1. Run an Angular project using 10.2.4 and handsontable 8.3.1
2. Create a component that generates a handsontable
3. Run project with --prod flag or with AOT and Build Optimiser on.
4. Handsontable will not display and will throw an error in the console

### Your environment
* Handsontable version: 8.3.1
* Browser Name and version: Chrome 88.0.4324.96 or Chrome Canary 90.0.4421.0 
* Operating System: Mac OS (Big Sur)
* Angular: v10.2.4 - with AOT and Build Optimiser set to true in the Angular.json.

**Comment by swistach** [comment]
Hi @rapelt,
Sorry for that inconvenience. We are working on a solution.
In the meantime, I close this issue due to it's a duplicate of #7577 - there you can track work progress.
