### PR TITLE
DEV-2020: Keep escape hatch on React wrapper prop types for undeclared options

### PR DESCRIPTION
**Pull request by budnix**
> [skip changelog] — corrects an unreleased regression from #13007 (still on develop, never released); #13007's own changelog entry covers the shipped behavior.

### Context

The PR fixes a build regression introduced by #13007 (DEV-2020) once it merged to `develop` (commit `1756d15b`). The "Build every package in different environments" workflow started failing in all three OS environments (macOS, Ubuntu, Windows) with the same error while building the docs React example `examples/next/docs/react-wrapper/accessibility`:

```
src/App.tsx(89,11): error TS2322: Type '{ data: string; dateFormat: {...}; correctFormat: true; type: string; allowInvalid: false; }'
  is not assignable to type 'IntrinsicAttributes & HotColumnProps'.
  Property 'correctFormat' does not exist on type 'IntrinsicAttributes & HotColumnProps'.
```

Root cause: #13007 made the React wrapper's `HotTableProps`/`HotColumnProps` strict (to restore prop autocomplete) by stripping the `[key: string]: any` index signature the raw settings types carry. That signature is also an escape hatch for cell-type/plugin options that are not declared on `GridSettings` — e.g. the `date` cell option `correctFormat`. Stripping it made those valid options a type error, breaking real configs.

Fix: re-add `& { [key: string]: any }` to the wrapper prop type (`ReplaceRenderersEditors`). The named options still keep their real types and IDE autocomplete — this is exactly the `React.CSSProperties` pattern, which autocompletes known properties yet still accepts arbitrary custom ones. So `<HotTable>`/`<HotColumn>` autocomplete (the #13007 fix) is retained, wrong types on *known* props are still caught, and undeclared-but-valid options are accepted again.

This is a types-only change in `@handsontable/react-wrapper`; runtime behavior is unchanged.

### How has this been tested?

- Reproduced the exact failing example (`accessibility` React example, TS 5.4, its tsconfig) against a fresh build of core + wrapper: fails before the change, **builds clean after**.
- Type behavior verified in isolation: undeclared option (`correctFormat`) accepted; `width`/`renderer` keep their real types; a wrong type on a known prop (`readOnly: 'nope'`) is still rejected.
- `npm run test --prefix wrappers/react-wrapper` — 75 passing (15 suites).
- The `accessibility` docs example that CI builds serves as the ongoing regression guard — it fails if the hatch is dropped again.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):

1. #12954
2. DEV-2020

### Affected project(s):

- [ ] `handsontable`
- [ ] `@handsontable/angular-wrapper`
- [x] `@handsontable/react-wrapper`
- [ ] `@handsontable/vue3`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [ ] My change requires a change to the documentation.

ClickUp task: https://app.clickup.com/t/9015210959/DEV-2020

---

> [!NOTE]
> **Low Risk**
> Declaration-only change in `@handsontable/react-wrapper`; no runtime behavior changes.
> 
> **Overview**
> Fixes a **types-only** regression where `HotTableProps` / `HotColumnProps` no longer accepted undeclared cell-type and plugin options (e.g. `correctFormat` on date columns), which broke docs examples and real configs.
> 
> `ReplaceRenderersEditors` in `types.tsx` now ends with **`& { [key: string]: any }`** again, alongside the existing `RemoveIndexSignature` + `Omit` work that keeps named-option autocomplete. Known props still use their real types and wrong values on those props are still rejected; extra keys stay assignable, matching the **`React.CSSProperties`** pattern.
> 
> **`AGENTS.md`** and **`react-wrapper-dev` SKILL** document that the hatch must not be dropped after stripping the index signature for `Omit`/`Pick`.
> 
> <sup>Reviewed by [Cursor Bugbot](https://cursor.com/bugbot) for commit 4ddc9725d2e067bf24e8a7939dfba402fce52e35. Bugbot is set up for automated code reviews on this repo. Configure [here](https://www.cursor.com/dashboard/bugbot).</sup>

### CODE REVIEW

**Comment by qunabu** [comment]
Task linked: [DEV-2020 Autocomplete editor does not auto-complete (React 19.2, v18.0) — #12954](https://app.clickup.com/t/9015210959/DEV-2020)

**Review by demtario — APPROVED** [review]
