### PR TITLE
Fix for react-redux.md docs compilation

### PR DESCRIPTION
**Pull request by NOtherDev**
### Context

[skip changelog]
Fix for documentation compilation error introduced in #10793.

### How has this been tested?

N/A - docs change

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1. #10793 

### Affected project(s):
- [ ] `handsontable`
- [ ] `@handsontable/angular`
- [x] `@handsontable/react`
- [ ] `@handsontable/vue`
- [ ] `@handsontable/vue3`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [x] My change requires a change to the documentation.

### CODE REVIEW

**Comment by NOtherDev** [comment]
@evanSe Docs in #10831 does not compile because of this overlooked issue. Let's merge in please 🙏

**Comment by NOtherDev** [comment]
Thx for merging @evanSe. This PR lead me to one more thought - the issue here was that the custom editor component was used outside of the `editor` prop (it was both a renderer and an editor in this case). It was failing on property access on `undefined` context at `useHotEditor`. Shall we maybe check it gracefully and issue a warning if someone places custom editor outside of `editor` prop?
