### PR TITLE
Add a keyboard shortcut that allows managing the cell comments

### PR DESCRIPTION
**Pull request by budnix**
### Context

The PR adds support for new keyboard shortcuts that allows managing the cell comments feature. The shortcut is active only when the _Comments_ plugin is enabled.

### Expected working new keyboard shortcuts
 - <kbd>Ctrl</kbd></kbd>+<kbd>Alt</kbd>+<kbd>M</kbd> Inserts or edits a comment.
Kapture 2023-06-26 at 10 56 56

 - <kbd>Ctrl/Cmd</kbd></kbd>+<kbd>Enter</kbd> Saves and exits the current comment;
Kapture 2023-06-26 at 10 57 40

 - <kbd>Escape</kbd> Exits from the current comment without saving;
Kapture 2023-06-26 at 10 58 18

The mouse interactions with comments have not been changed. Once the comment is edited and the mouseover event is triggered, the comment value is saved into the cell meta.

While testing the PR, @aninde found a bug that was throwing errors when the keyboard shortcut was used on the cell that was selected but not rendered - the cell was not visible in the tables viewport. This [commit](https://github.com/handsontable/handsontable/pull/10421/commits/208afb86f6fc82aabe7e3f04c6bf4566c62f2c83) fixes that bug. Also, the change fixes a similar bug in the _ContextMenu_ plugin. The changes resulted in the addition of 2 new functionalities:
 * New Core method that allows scrolling the viewport to the focused cell `hot.scrollToFocusedCell()`;
 * New hook `afterScroll` that allows listening for changes in the horizontal or vertical scrolls;

### How has this been tested?

I tested the changes locally, and I covered the feature with new E2E tests.

### Types of changes

- [x] New feature or improvement (non-breaking change which adds functionality)

### Related issue(s):
1. fixes https://github.com/handsontable/dev-handsontable/issues/1375

### Affected project(s):
- [x] `handsontable`

### Checklist:

- [x] I have reviewed the guidelines about [Contributing to Handsontable](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md) and I confirm that my code follows the code style of this project.
- [x] I have signed the [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1)
- [x] My change requires a change to the documentation.

### CODE REVIEW

**Comment by budnix** [comment]
@kirszenbaum, and here is another keyboard shortcut that needs to be added to https://github.com/handsontable/handsontable/pull/10402.

**Review by aninde — CHANGES_REQUESTED** [review]
During acceptance testing I managed to found use case thats throws an error.

Steps to reproduce:
On demo where Handsontable has set height: '150px' and perpendicularly scroll bar https://jsfiddle.net/aninde/Lu2p8rvh/ with this [build](https://www.npmjs.com/package/handsontable/v/0.0.0-next-c3d199b-20230626)
1. Select cell B1
2. Scroll down vertical 10 rows down
3. Click Ctrl + Alt + M to insert comment

**Actual result**: Error in the console. Comment text area opens up, but without focus inside. Regardless of the location of the cell lying outside the viewport to which the comment is added with these settings, the comment opens at the top of the table
```
handsontable.full.min.js:528 Uncaught TypeError: T.getBoundingClientRect is not a function
    at n.value (handsontable.full.min.js:528:220521)
    at n.value (handsontable.full.min.js:528:219427)
    at callback (handsontable.full.min.js:528:215676)
    at handsontable.full.min.js:883:49528
    at HTMLHtmlElement.f (handsontable.full.min.js:883:53027)
```

https://github.com/handsontable/handsontable/assets/30186818/02a7803f-9a8f-4f19-bdf5-7e52f7d395c9


With height: 'auto' https://jsfiddle.net/aninde/90tn4ec there is no issue. 

https://github.com/handsontable/handsontable/assets/30186818/658ac265-db17-43b9-a0e4-9f6db07421f1

**Comment by budnix** [comment]
> During acceptance testing I managed to found use case thats throws an error.

Thanks for spotting that. I fixed it within https://github.com/handsontable/handsontable/pull/10421/commits/208afb86f6fc82aabe7e3f04c6bf4566c62f2c83

**Comment by kirszenbaum** [comment]
Documented in #10402

**Comment by AMBudnik** [comment]
Works well in v14.0.0 https://jsfiddle.net/mns5rjkz/14/
